### PR TITLE
Refined (in my opinion(!)) the es Spanish translations.

### PR DESCRIPTION
**Pull request by stellarpower**
Just tidied-up some of the translations, fixing spelling and punctuation errors (and as far as I can tell adding no more but I can double check for typos again later), rewording things slightly to give, in my opinion, a better sense of the original and changing a couple of Latin-American-specific words to standard Spanish. I've tried to copy the capitalisation and spacing exactly. If there are problems with the length of the strings I can cut them down slightly.

### CODE REVIEW

**Comment by alballena** [comment]
I agree. It's a better translation.

**Comment by stellarpower** [comment]
Just realised that I say 'reloj' in a few places where I should say 'temporizador' - for consistency I'll change that when I have my sources and submit a new pull request.

**Comment by alballena** [comment]
* The wording is fine.

* _Pomodoro_/_Pomodori_ capitalization is inconsistent.

* I would change to lowercase on _Nuevo_, _Comenzará_, _Reloj_, _Sonido_, _Descanso_, etc.

By the way, I don't have write access u_u.

**Comment by gfreeau** [comment]
Thanks for the pull request, once you are happy with it I will merge it.

**Comment by gfreeau** [comment]
Is this ready to be merged?

**Comment by stellarpower** [comment]
@alballena Changed the inconsistencies on Pomodoro/Pomodori. I was trying to match the case of the original, so I used capitalisation on non-trivial words where the same was done in English. I didn't know that formally titles basically use sentence case, so I've changed that. Okay with you?

**Comment by gfreeau** [comment]
Ok with me. Thank you for the contribution.

**Comment by stellarpower** [comment]
Really sorry I didn't get back to you sooner!

**Pull request merged**
